### ISSUE TITLE
semifinal 1st setのLOSE判定のエラー

### ISSUE THREAD

**Issue by MUQuizProject** [nano-nano/vbc_on_web#1]
![FireShot Capture 008 - vbc on Web - localhost](https://user-images.githubusercontent.com/16572733/91660801-e6a91200-eb12-11ea-8e90-77a15f958b0b.png)
![FireShot Capture 011 - vbc on Web - localhost](https://user-images.githubusercontent.com/16572733/91660836-1ce69180-eb13-11ea-8df4-7717d70acd99.png)

何回かサンプルデータで回してみましたが，準決勝のポイント判定の部分に不具合があるようです．明らかにptの大小関係とLOSEが違っている部分があります．

**Comment by nano-nano** [comment]
ポイントでソートする際のソート関数が十分に実装されていないのが原因な気がする……

**Comment by nano-nano** [comment]
ソート関数を修正
また、敗者復活無しのときに1stセットの敗退人数を調整し損ねていたので修正
